### ISSUE TITLE
Just use JS?

### ISSUE THREAD

**Issue by tony** [Mrtenz/gatsby-plugin-aws-elasticsearch#9]
I feel odd saying this.  I'm maintaining [a fork](https://github.com/tony/gatsby-plugin-aws-elasticsearch) of this now and am converting it to JS. I probably will tomorrow

I love TypeScript, your code in `src/` is good. But it's making it difficult to change/test the plugin itself, Gatsby doesn't doesn't handle typescript configs and plugins well at this time.

Namely, if I want to edit the plugin (i have it as a submodule), I have to rebuild it in TS.

I dream something like this https://github.com/gatsbyjs/gatsby/discussions/31587 will gain traction and TS would just "work"

What is your position on this?  Do you think TypeScript helps much if gatsby doesn't work with it?

**Comment by tony** [comment]
![image](https://user-images.githubusercontent.com/26336/120054345-06fbf380-bff5-11eb-917c-8a0b9ea0e511.png)

No!!!

**Comment by Mrtenz** [comment]
I have no plans to convert the plugin to plain JavaScript. TypeScript provides, in my opinion, a big benefit regardless of whether Gatsby fully supports it. I personally use [`gatsby-plugin-ts-config`](https://github.com/Js-Brecht/gatsby-plugin-ts-config) in my Gatsby projects to write the configuration in TypeScript as well.

You should be able to test the plugin by using `yarn build` and `yarn link`.

**Comment by tony** [comment]
I'm aware of `yarn build` and `yarn link` (I don't need to run that since I'm using a monorepo with this in a submodule), but even without those, modifying the plugin itself is hard. I think our repos are at a hard fork at this point.  

> I personally use [`gatsby-plugin-ts-config`](https://github.com/Js-Brecht/gatsby-plugin-ts-config) in my Gatsby projects to write the configuration in TypeScript as well.

I'll look into this. It's actually by the same author as this post https://github.com/gatsbyjs/gatsby/discussions/31587.

Even then, my issue is it's not native and it makes it harder to develop the plugin itself.  Does that make sense?  JS just works. TS requires a lot of ceremony.

I like TypeScript, if this were a non-gatsby NPM package, it wouldn't be an issue. From a devops perspective gatsby not working with TS natively makes it a hindrance rather than a help.

**Comment by Mrtenz** [comment]
> modifying the plugin itself is hard

Hard because the code is difficult to understand (due to TypeScript), or because it's difficult to get Gatsby to work with the plugin? In the latter case, if you're using it as a submodule, you can probably use a simple watch script (`yarn babel --watch`?) to automatically transpile the code to something that Gatsby supports natively.

> Even then, my issue is it's not native and it makes it harder to develop the plugin itself. Does that make sense? JS just works. TS requires a lot of ceremony.
>
> I like TypeScript, if this were a non-gatsby NPM package, it wouldn't be an issue. From a devops perspective gatsby not working with TS natively makes it a hindrance rather than a help.

I think the benefit of knowing what types you're working with is definitely worth it. Gatsby has (limited) types built-in, as you can see in [`index.ts`](https://github.com/Mrtenz/gatsby-plugin-aws-elasticsearch/blob/main/src/index.ts). And since it compiles to native JavaScript, you don't need TypeScript in your own Gatsby project to use this plugin.

Like I mentioned earlier, I'm not planning on converting the plugin to JavaScript, but you're of course free to make your own version of this plugin! I made it initially for use in a single project (we use it [here](https://github.com/MyCryptoHQ/knowledge-base)), but decided to deploy it to NPM becasue it _may_ be useful to others as well.

**Comment by tony** [comment]
Thanks for showcasing [your project](https://github.com/MyCryptoHQ/knowledge-base) and letting me know your disposition on the package itself

> Hard because the code is difficult to understand (due to TypeScript), or because it's difficult to get Gatsby to work with the plugin

I love TypeScript and consider myself proficient in it.  I know how to get Gatsby to work with the plugin and detect it.

However, when it comes to developing TypeScript Gatsby Plugins, I'm absolutely vexxed.  I used to maintain my gatsby-config/gatsby-node/etc files in TS but changed back when file changes were missed and things would break.

I am trying to get `gatsby-plugin-aws-elasticsearch` to work with plain-old ElasticSearch locally, so I'm editing the project itself and restarting gatsby.  I'm speaking about the development loop - Doesn't TypeScript mean more steps? Don't I need to rebuild every time I made a change to `gatsby-plugin-aws-elasticsearch`?

Aside: To your point, I just found this:

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-page-creator

That's an officially maintained gatsby package using TypeScript. :shrug:
